# Generated by Django 4.2.7 on 2023-11-04 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessroom',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessroom',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewerslist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessroom',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whiteuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
