# Generated by Django 4.2.7 on 2023-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chessroom_black_alter_chessroom_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessroom',
            name='Board',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='chessroom',
            name='Color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessroom',
            name='Moves',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
