# Generated by Django 4.2.7 on 2023-11-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chessroom_board_chessroom_color_chessroom_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessroom',
            name='Board',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=72),
        ),
        migrations.AlterField(
            model_name='chessroom',
            name='Moves',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
