# Generated by Django 4.2.7 on 2024-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_guessroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessroom',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
