# Generated by Django 4.2.7 on 2024-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_guessroom_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guessroom',
            name='guess1',
        ),
        migrations.RemoveField(
            model_name='guessroom',
            name='guess2',
        ),
        migrations.RemoveField(
            model_name='guessroom',
            name='viewers',
        ),
    ]
